name: Keep Render App Alive

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes

  workflow_dispatch:  # Allows manual execution of the workflow

jobs:
  keep_alive:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu virtual machine

    steps:
      - name: Ping Render API
        run: |
          curl -X GET "https://potato-leaf-disease-api.onrender.com/ping"
